### ISSUE TITLE
Request for a demo

### ISSUE THREAD

**Issue by nanma** [iani/org-publish-meta#5]
This project is great, but the readme and tutorial seems complicated，could you write a short demo to show its usage? I want to use org-mode to publish post to jekyll, I think this project would fit my need.

**Comment by iani** [comment]
Hello Nan Ma, 
thanks for writing. I'll try to respond to you within the next days with a short demo. 

Iannis Zannos

**Comment by nanma** [comment]
Thanks Iannnis, it would be very helpful.
